### ISSUE TITLE
Frontend only returns HTTP 403

### ISSUE THREAD

**Issue by gegenschall** [rnwood/smtp4dev#1563]
I'm using smtp4dev with Docker Compose like so:
```yaml
services:
   smtp:
    image: rnwood/smtp4dev
    restart: always
    volumes:
      - smtpdata:/smtp4dev
    ports:
      - '5000:80'
```

The server starts up just fine and reports it's running on ports 80, 25 and 143 for HTTP, SMTP, and IMAP. When I open a browser to `http://localhost:5000` I am only presented with a HTTP 403 error with an empty respose. 

Is there anything I need to configure to make the frontend work? I couldn't find anything in the docs.
