### ISSUE TITLE
Always receiving "Internal Server Error" with naive Traefik configuration

### ISSUE THREAD

**Issue by TuringTux** [rnwood/smtp4dev#1618]
I need to run smtp4dev behind a Traefik reverse proxy. While smtp4dev works nicely on its own, when reverse-proxying the requests, I am met with an HTTP 500 (Internal Server Error).

You can use this Docker Compose file to reproduce:

```yaml
services:
    proxy:
        image: traefik:latest
        ports:
            - "80:80"
        command:
            - --providers.docker
            - --entrypoints.web.address=:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    smtp4dev:
        image: rnwood/smtp4dev
        ports:
            - "81:80"
        labels:
            - traefik.http.routers.smtp4dev.rule=Host(`localhost`)
```

After starting this with

```
docker compose up
```

try accessing the following URLs:

* http://localhost:81 — This will work (directly accessing the webserver in smtp4dev, without a reverse proxy)
* http://localhost:80 — **This will not work** (accessing the webserver via the Traefik reverse proxy)

To check that Traefik is set up correctly, try replacing `rnwood/smtp4dev` with `httpd` to run a basic Apache server, which will respond under http://localhost:80.

Does smtp4dev choke on some of the HTTP headers that Traefik sends? Sadly, I am not seeing much debug output in smtp4dev either, but I can of course test things when necessary.

Thanks in advance :)

**Comment by TuringTux** [comment]
✅ I figured it out. The problem is that **Traefik tries to route the HTTP requests to port 25 (the SMTP server)**. This can be fixed by manually telling Traefik where to route the HTTP requests to, e.g., like this:

```yaml
services:
    proxy:
        image: traefik:latest
        ports:
            - "80:80"
        command:
            - --providers.docker
            - --entrypoints.web.address=:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    smtp4dev:
        image: rnwood/smtp4dev
        ports:
            - "81:80"
        labels:
            - traefik.http.routers.smtp4dev.rule=Host(`localhost`)
            - traefik.http.services.smtp4dev-service.loadbalancer.server.port=80
```

Adding the **`traefik.http.services.smtp4dev-service.loadbalancer.server.port=80`** line as described above was necessary (see also https://doc.traefik.io/traefik/routing/providers/docker/#routing-configuration for more details).

So, everything with `smtp4dev` works as expected. Sorry for bothering you, have a nice weekend!
