### ISSUE TITLE
415 Unsupported Media Type whe using /api/Messages/send

### ISSUE THREAD

**Issue by luistar15** [rnwood/smtp4dev#1628]
When trying to send a email message through de API I always get 415 response.

```yaml
services:
  smtp:
    image: rnwood/smtp4dev:3.7.0-ci20250120116
    ports:
      - 7078:25
      - 7079:80
```

Generated via http://localhost:7079/api/index.html#/Messages/Messages_Send
```bash
curl -X 'POST' \
  'http://localhost:7079/api/Messages/send?to=target%40localcom&from=me%40local.com&subject=Hello' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '"Hi"'
```

```yaml
HTTP/1.1 415 Unsupported Media Type
Content-Length: 0
Connection: close
Date: Sun, 16 Feb 2025 15:00:25 GMT
Server: Kestrel
```
