### ISSUE TITLE
Unable to run container images with `npm` error

### ISSUE THREAD

**Issue by brettinternet** [rnwood/smtp4dev#1750]
Hi, trying out your software within docker, I'm getting this error:

```
An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (One or more errors occurred. (Failed to start 'npm'. To resolve this:.

...
```

I've tried a few different tags with this error such as `v3`, `v3.8`, `3.8.7-ci20250525101`, `3.8.7-ci20250513100`, `linux-arm64-3.8.7-ci20250525101`.

```yaml
smtp4dev:
    image: rnwood/smtp4dev:3.8.7-ci20250525101
    container_name: smtp4dev
    environment:
      ServerOptions__Urls: http://mail.mysite.arpa
    volumes:
      - ./docker/data/smtp4dev:/smtp4dev
    ports:
      - "25:25"
    labels:
      traefik.enable: true # my reverse proxy
      traefik.http.routers.smtp4dev.rule: Host(`mail.mysite.arpa`)
      traefik.http.routers.smtp4dev.entrypoints: web
      traefik.http.services.smtp4dev.loadbalancer.server.port: 80
```

Are the dockerfiles missing a Node dependency?
