### ISSUE TITLE
Document configuration options and add command line help

### ISSUE THREAD

**Issue by rnwood** [rnwood/smtp4dev#296]

**Comment by sibrus** [comment]
This would be appreciated :)

I just figured this out on my own by reading the source and trying stuff. In my case, I wanted TLS disabled to not have to worry about dealing with the self-signed cert when everything is on one host.

I also came up with a docker-compose.yml file that includes my options, maybe it can be a useful example:

```yaml
version: '3'

services:
  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp
    restart: always
    ports:
      - '9200:80'
      - '2525:25'
    entrypoint: ["dotnet", "/app/Rnwood.Smtp4dev.dll", "--tlsmode", "None"]
```
