### ISSUE TITLE
Issue "Connection refused" when running under docker-compose

### ISSUE THREAD

**Issue by atresnjo** [rnwood/smtp4dev#306]
Thanks for the project, really cool! I got it instantly working with running the docker image, but now I was trying to integrate it into my docker-compose but so far no luck. I keep getting "connection refused" using MailKit. Any ideas? Thanks a lot! :)

![grafik](https://user-images.githubusercontent.com/41112852/78049289-2b215d80-737b-11ea-9cfa-f936ccde789e.png)

![grafik](https://user-images.githubusercontent.com/41112852/78049260-20ff5f00-737b-11ea-9dc1-dba5649b0f0a.png)

```yaml
version: '3.4'

networks:
  jobbrapi-dev:
    driver: bridge 

services:
  jobbrapi:
    image: jobbrapi:dev
    depends_on:
      - "postgres_image"
      - "jobbr_mail_server"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"  
      MailServiceSettings:Host: "jobbr_mail_server"
    ports:
      - "8000:80"    
    networks:
      - jobbrapi-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "jobbr"
    networks:
      - jobbrapi-dev

  jobbr_mail_server:
    image: rnwood/smtp4dev:v3
    ports:
      - "2525:25"
      - "3000:80"
    networks:
      - jobbrapi-dev
      
volumes:
  db_volume:
```
