### ISSUE TITLE
Docker-compose SSL

### ISSUE THREAD

**Issue by salarmehr** [rnwood/smtp4dev#772]
Thanks for this awesome tool.

Here is my docker-compoe.yml service. 

```
    mail: 
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
            - ${APP_IP}:5000:80
        volumes:
            - mail:/smtp4dev
            - ./docker/ssl:/ssl
        networks:
            - backend
        environment:
            - ServerOptions__HostName=jimble.dev
            - ServerOptions__TlsMode=ImplicitTls
            - ServerOptions__TlsCertificate=/ssl/server.crt
```
I don't know how to set the cert key as it's not mentioned on https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml 

I have a cert file that I use for my Apache and Node serve (along with the cert key file)  and both work well. However, using the same cert file as blew does not work and I get the following error (using HTTPie)

```
https foo.dev:5000/

https: error: SSLError: HTTPSConnectionPool(host='jimble.dev', port=5000): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)'))) while doing a GET request to URL: https://jimble.dev:5000/
```
And on Firefox
```
Secure Connection Failed

An error occurred during a connection to jimble.dev:5000. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```
